### ISSUE TITLE
Create Movement Validation

### ISSUE THREAD

**Issue by dboone** [dboone/rusty-checkers#1]
@drbassett Try and attach your image here.

**Comment by drbassett** [comment]
![Simple move](https://cloud.githubusercontent.com/assets/12978641/8322527/ac829b08-1a04-11e5-8555-3105b7543714.png)

**Comment by drbassett** [comment]
Computing multi-jump moves will have to be done recursively. Is it possible that there could be a sequence of jumps that end up in a loop? The only cases I can come up with involve the moving piece reaching its starting position, which won't break the algorithm I have in mind, since it will see that tile as blocked.

**Comment by dboone** [comment]
Did someone say `rustcursion`?

**Comment by dboone** [comment]
You are talking about computing moves, but if the attacked pieces were "removed" from the board we wouldn't have to worry about loops.

Also, the loop in question could only occur for a king piece. Unless a man can be crowned during a jump. I'm thinking that's not legal though.

**Comment by dboone** [comment]
What do you have in mind regarding the allowed direction of travel for the men?

**Comment by dboone** [comment]
Pieces have certain intrinsic movement properties, but a bird's eye view of the board is required to validate their moves.

## Piece level movement validation

All pieces can move one space at a time along the diagonals, except when jumping. Once a man reaches the opposite side of the board (can no longer move forward), he is crowned and becomes a king. Need a crown function?
- Man - can only move forward
- King - can forward or backward

## Board level movement validation

Checking for and validating jumps:
- Destination space must be reachable at a piece level and be an `EmptyTile`.
- Check for opponent piece between current tile and destination tile.
- A player must take any single jumps they are presented with.
- Multi-jumps are left to the player's discretion.
- more...

**Comment by drbassett** [comment]
Going back to my original comment on recursion...

I am writing a function that computes all of the available moves for a player. We need this capability to (1) determine if the player has jumps that they are required to take, and (2) for a future AI player to use. In this function, I am not updating the board, only observing it. So, I am not removing pieces from the board as I go. I am trying to determine if we need to keep track of the pieces we jumped or not, so that we don't try to jump a piece twice. As far as I can tell, if we just use a recursive algorithm, we do not.

**Comment by drbassett** [comment]
I take that back. Just came up with this situation:

![infinite-recursion](https://cloud.githubusercontent.com/assets/12978641/8370571/9014f2a6-1b97-11e5-9505-1d2af1809558.png)

(notice that I fixed my wood texture on the dark squares in this picture too)

**Comment by dboone** [comment]
That is a good test case.

And it isn't as simple as keeping track of the tiles we have visited because a tile can be visited multiple times during the jump.

This would be the worse case scenario. Start with 1 at the bottom left corner.

```
[   ][   ][   ][   ][   ][   ][   ][   ]
[   ][   ][ 8 ][   ][   ][   ][ 10][   ]
[   ][  O][   ][  O][   ][  O][   ][   ]
[  7][   ][   ][   ][5/9][   ][   ][   ]
[   ][  O][   ][  O][   ][  O][   ][   ]
[   ][   ][2/6][   ][   ][   ][  4][   ]
[   ][  O][   ][  O][   ][  O][   ][   ]
[  1][   ][   ][   ][  3][   ][   ][   ]
```

This path is not unique either.

**Comment by dboone** [comment]
This would be the worse case scenario. Start as `X` at the bottom left corner.
```
[ ][ ][ ][ ][ ][ ][ ][ ]
[ ][ ][X][ ][ ][ ][X][ ]
[ ][O][ ][O][ ][O][ ][ ]
[X][ ][ ][ ][x][ ][ ][ ]
[ ][O][ ][O][ ][O][ ][ ]
[ ][ ][X][ ][ ][ ][X][ ]
[ ][O][ ][O][ ][O][ ][ ]
[X][ ][ ][ ][x][ ][ ][ ]
```

**Comment by drbassett** [comment]
Note that I said we need to keep track of the _pieces_ we jumped, not the tiles. That should make your example work. We can land at the same tile multiple times, but we can't jump over the same tile multiple times. Not unless we are playing Indian checkers, where the pieces can reincarnate.

**Comment by dboone** [comment]
Keeping track of the pieces jumped seems solid. You can't jump the same piece twice so you don't have to worry about loops. Both examples work.

If you jump all the pieces then you win.
